########################################################################################
#
#  DO NOT EDIT THIS FILE!!
#
########################################################################################

# This file should be commited to the repository. It makes it possible to set module
# specific environmental variables. Do not change this file if you check out a project
# Instead copy this file:
#   cp default.mk local.mk
# Then change that file and NOT commit "local.mk" to the repository. It should be only
# used locally. At any times the "default.mk" file will be overwriting by the global 
# configuration file "~/.rur/rur.mk" and which is overwitten again by "local.mk".
# 

# Default backend to be used, it can also be YARP or ROS
set(BUILD_ZEROMQ on)

#RUR_BACKENDS is impossible to set here, because it depends on your system configuration
# it should end with something like rur-builder/backends.
