#!/bin/make

# Author: Anne C. van Rossum
# Date: Mar. 31, 2013

# We don't need to build anything
.PHONY: all
all: 
	@echo "[*] Only installation is required"

# We only install (need to be sudo)
.PHONY: install
install:
	@sh install.sh

