/**
 * IDL description of the WriteModule
 *
 * This file is automatically parsed by the rurbuilder backends for the omniidl 
 * compiler. The names of the functions will become port identifiers. The names 
 * of the function variables are not used. For now, if the function variable 
 * ends with a number, like "void Sensor(in long input2);" there will be two
 * portnames created.
 */

#pragma author Anne C. van Rossum
#pragma copyright Distributed Organisms B.V.
#pragma date Mar. 27, 2013
#pragma license LGPLv3

// Recommended namespace "rur"
module rur {

// We want to be able to give our class a name
interface WriteModule {

  // Output is one value each time
  void Output(out long output);

};

};
