// The recommended namespace is Rur
module Rur {

// There is a dedicate Param struct that can be used to define command-line
// parameters
struct Param {
	long sensor_id;
};

typedef sequence<double> long_seq;

// The name of the module (should end with Module)
interface SumModule {

  // This channel goes "in" and will become the method "int *readInput()".
  void Input(in long_seq data_in);

  // This becomes the method "writeOutput(const int data_out)"
  void Output(out long data_out);

};

};
