#!/bin/bash

PROGRAM="aimcreate-pkg"

VERSION="$PROGRAM 0.1"

if [[ "$1" == "" ]]
then
	echo "No args supplied! Run $0 -h for more info"
	exit 1
fi

if [[ "$1" == "-h" ]]
then
	echo $VERSION \- Usage
	echo 
	echo $PROGRAM \"ModuleName\"
	echo
#	echo \* recipient_number - The recipients phone number. Without the country number
#	echo \* \"message\" - Defines the message to send. The \"\" are mandatory
	exit 0 
fi 

modulename="$1"

# Check if there are no whitespaces
mn_sanity_check=${modulename//[[:space:]]}

if [[ "$mn_sanity_check" == "$1" ]]; then
	if [[ "$1" == *Module ]]; then
		echo "Thanks, $1 is a proper module name"
	else
		echo "Please, end the module with \"Module\""
		exit 1
	fi
else
	echo "Please, do not use whitespaces"
	exit 1
fi

# Create the proper directory
mkdir -p "$modulename"
cd "$modulename"

# Copy from template directory
RUR_TEMPLATES=/var/lib/rur
cp -r $RUR_TEMPLATES .

# Have all AIM relevant stuff collected in one directory "aim"
mv rur aim
cd aim

# Adapt scripts to $modulename
sed -i "s/TemplateModule/$modulename/g" build.sh
sed -i "s/TemplateModule/$modulename/g" CMakeLists.txt
sed -i "s/TemplateModule/$modulename/g" Makefile
sed -i "s/TemplateModule/$modulename/g" TemplateModule.idl
sed -i "s/TemplateModule/$modulename/g" TemplateModuleMain.cpp
sed -i "s/TemplateModule/$modulename/g" TemplateModule.cpp

mkdir -p scripts
mv build.sh scripts
mv run.sh scripts

mkdir -p idl
if [ -a "idl/$modulename.idl" ]; then
	echo "The idl file exists, will not be overwritten"	
else
	mv TemplateModule.idl "idl/$modulename.idl"
fi

mkdir -p src
mkdir -p inc

mv TemplateModuleMain.cpp "src/${modulename}Main.cpp"
mv TemplateModule.cpp "src/${modulename}.cpp"

