########################################################################################
#
#  DO NOT EDIT THIS FILE!!
#
########################################################################################

# This file should be commited to the repository. It makes it possible to set module
# specific environmental variables. Do not change this file if you check out a project
# Instead copy this file:
#   cp default.cmake local.cmake
# Then change THAT file and NOT commit "local.cmake" to the repository. It should ONLY
# be used locally. At any times the "default.cmake" file will be overwritten by the
# global configuration file "~/.rur/rur.mk" and which is overwitten again by 
# "local.cmake".
# 
# Default backend to be used, it can be:
#   BUILD_STANDARD, BUILD_YARP, BUILD_ROS, or BUILD_ZEROMQ
set(BUILD_STANDARD on)

