#!/bin/bash

PROGRAM="aimlogin"

VERSION="$PROGRAM 0.1"

# Check if we have sudo rights
if [ `id -u` -eq 0 ]
then
	echo "Sorry, should not be run as super user"
	exit 1
fi

if [[ "$1" == "" ]]
then
	echo "No args supplied! Run $0 -h for more info"
	exit 1
fi

if [[ "$1" == "-h" ]]
then
	echo $VERSION \- Usage
	echo 
	echo $PROGRAM \"identifier\"
	echo
	exit 0 
fi 

# mode or phase, authorisation can be a multi-step procedure
MODE=${1%/}

# token
TOKEN=${2%/}

# stdout is used as input for the nodejs server, so do not print 
# things by accident to stdout

if [[ "$MODE" == "oauth0" ]]
then
	#echo "aimrun CSLoginModule $MODE $TOKEN"
	rm -f result.txt
	aimrun CSLoginModule $MODE $TOKEN 1>result.txt
	key=`cat result.txt | grep ^key | grep -v "'" | cut --delimiter=" " -f2`
	secret=`cat result.txt | grep ^secret | grep -v "'" | cut --delimiter=" " -f2`
	echo $key
	echo $secret
else if [[ "$MODE" == "oauth1" ]]
then
	#echo "aimrun CSLoginModule $@"
	rm -f result1.txt
	aimrun CSLoginModule "$@" 1>result1.txt
	key=`cat result1.txt | grep ^key | grep -v "'" | cut --delimiter=" " -f2`
	secret=`cat result1.txt | grep ^secret | grep -v "'" | cut --delimiter=" " -f2`
	echo $key
	echo $secret
fi
fi

