#!/bin/make

# Author: Anne C. van Rossum
# Date: Aug. 04, 2011

# This include file should define BACKEND
#include local.mk

RUR_TEMPLATES=/var/lib/rur

# We don't need to build anything
.PHONY: all
all: 
	@echo "[*] Only installation is required)"

# We only install (need to be sudo)
.PHONY: install
install:
	@sh install.sh

