#!/bin/bash

PROGRAM="aimrun"

VERSION="$PROGRAM 0.1"

# For default execution of things that only run on the server we need 2 arguments
if [[ $# -lt 2 ]]
then
	echo "Not enough args supplied! Run $0 -h for more info"
	exit 1
fi

# For execution of modules that connect to CommonSense we need 4 arguments
# We do not check for that here...

if [[ "$1" == "-h" ]]
then
	echo $VERSION \- Usage
	echo 
	echo $PROGRAM \"ModuleName\" \"ModuleId\"
	echo
	exit 0 
fi 

MODULE_NAME=${1%/}
ModuleId=${2%/}

# Configuration directory for RUR
RUR_HOME=~/.rur
mkdir -p ${RUR_HOME}

AIM_REGISTRY=aim_registry.txt

echo "Search in ${RUR_HOME}/${AIM_REGISTRY}"
SUCCESS=false
MODULE_FULLNAME=
while read LINE; do
	MODULE_I=`echo "$LINE" | cut -d'=' -f 1`
	M_I_STRIPPED=${MODULE_I//[[:space:]]}
#	echo $M_I_STRIPPED
	if [[ "$M_I_STRIPPED" == "$1" ]]; then
#		echo "$MODULE_NAME found. Run it"
		MODULE_FULLNAME=`echo "$LINE" | cut -d'=' -f 2`
		SUCCESS=true
		break
	fi
done < "${RUR_HOME}/${AIM_REGISTRY}"

# Shift so, $@ becomes second argument (id) and further on
shift

if [[ $SUCCESS == true ]]; then
	# echo "Kill previous one"
	# pkill -9 $MODULE_NAME
	echo "Run $MODULE_FULLNAME/build/$MODULE_NAME $@"
	# yarp clean
	$MODULE_FULLNAME/build/$MODULE_NAME "$@"
else
	echo "No such module found ($MODULE_NAME)"
fi

exit 0
