#!/bin/bash

PROGRAM="aimcross"

VERSION="$PROGRAM 0.1"

####################################################################################################
# Configuration
####################################################################################################

# Installation paths, the bin path is to store the application itself, the share path to store 
# additional details such as helper python files, icons, translations. The config path to store 
# configuration details, such as starting at booting.
AIM_BIN_PATH=/usr/bin
AIM_SHARE_PATH=/usr/share/aim
AIM_CONFIG_PATH=/etc/aim
AIM_CROSSCOMPILECONF_PATH=$AIM_SHARE_PATH/crosscompileconf

# Update paths by prepending it with DESTDIR so installation via the Ubuntu PPA works properly. This
# causes a duplicate "//" when $DESTDIR is empty, which is no problem at all, just does not look so
# nice.
AIM_BIN_PATH="$DESTDIR/$AIM_BIN_PATH"
AIM_SHARE_PATH="$DESTDIR/$AIM_SHARE_PATH"
AIM_CONFIG_PATH="$DESTDIR/$AIM_CONFIG_PATH"
AIM_CROSSCOMPILECONF_PATH="$DESTDIR/$AIM_CROSSCOMPILECONF_PATH"

# Default configuration files
AIM_CONFIG_COLOR=$AIM_CONFIG_PATH/color.sh
AIM_CONFIG_SANITY=$AIM_CONFIG_PATH/sanity.sh

####################################################################################################
# Tweaks and general configuration details
####################################################################################################

source $AIM_CONFIG_COLOR
source $AIM_CONFIG_SANITY

####################################################################################################
# Checks
####################################################################################################

if [[ "$1" == "" ]]
then
	msg_error "No args supplied! Run $0 -h for more info"
	exit 1
fi

if [[ "$1" == "-h" ]]
then
	echo $VERSION \- Usage
	echo 
	echo $PROGRAM \"ModuleName\"
	echo
	exit 0 
fi 

modulename="$1"

aim_sanity $modulename error
if [[ "$error" != 0 ]]; then
	msg_error "Module name check failed, we quit"
	exit 1
fi

####################################################################################################
# Start
####################################################################################################

cd "$modulename"

################################################################################
# Checking and including stuff
################################################################################

target=$2

if [[ "$target" == "" ]]
then
	msg_warning "Use $0 with argument \"module name\" \"target\""
	exit 1
fi

case "$target" in 

"blackfin")
	msg_info "Cross-compile for \"blackfin\" processor"
;;
"raspberry")
	msg_info "Cross-compile for the \"Raspberry PI\""
;;
*)
	msg_error "Currently supported target architectures: \"blackfin\" and \"raspberry\""
	exit 1
;;
esac

#msg_info "Set installation dir and get color config"
#source /etc/apt-cross/ac-build/ac_get.sh

msg_info "Get platform specific compiler"
if [[ ! -e $AIM_CROSSCOMPILECONF_PATH/$target.sh ]]; then
	msg_error "File for target architecture does not exist: $AIM_CROSSCOMPILECONF_PATH/$target.sh"
	exit 1
fi
source $AIM_CROSSCOMPILECONF_PATH/$target.sh

#cd $AC_INSTALL_DIR
#echo "[#] Display directories in $AC_INSTALL_DIR: "
#echo "----------------------------------------"
#LIST="ls -d -1 */"
#eval $LIST
#echo "----------------------------------------"

#echo "[#] Go to $extracted_dir_mask"
#cd $extracted_dir_mask
#package_dir=$(pwd)
#echo "[#] Arrived in $package_dir"

################################################################################
# Requires cmake build system
################################################################################

LOG_FILE=make.log
 
# Sets "CORES" and "AVAILABLE_CORES"
set_cores() {
	CORES=1
	AVAILABLE_CORES=$(nproc)
	msg_info "We will compile on ${CORES} of a total of ${AVAILABLE_CORES} cores"
	msg_info "Note that Unity/Ubuntu grinds to a halt if this reaches the total number of cores available)"
}
 
set_verbosity() {
	MAKE_VERBOSITY="VERBOSE=1"
	MAKE_VERBOSITY=
}
 
set_timing() {
        MAKE_TIMING=time
}
 
# Create log file and write everything to it
# Prerequisite for check_errors and check_warnings
set_logging() {
	rm -f ${LOG_FILE}
	PIPE_TO_FILE="3>&1 1>&2 2>&3 | tee ${LOG_FILE}"
}
 
# A log file is a prerequisite, assumes we are still in the build directory
# so create the script file in the parent directory ..
check_errors() {
	msg_debug "Check for errors"
	CHECK_FOR_ERROR="egrep '(error|instantiated from|relocation truncated)'"
	CHECK_FOR_ERROR_CMD="cat ${LOG_FILE} | ${CHECK_FOR_ERROR} | head -n 1"
	ERRORS=`eval ${CHECK_FOR_ERROR_CMD}`
	ERROR_SCRIPT=../check_error.sh
	rm -f ${ERROR_SCRIPT}
	if [ -n "$ERRORS" ]; then
		ERROR_FILE=`eval ${CHECK_FOR_ERROR_CMD} | cut -d':' -f1`
		ERROR_LINE=`eval ${CHECK_FOR_ERROR_CMD} | cut -d':' -f2`
		echo "#!/bin/bash" >> ${ERROR_SCRIPT}
		echo "# -- automatically generated --" >> ${ERROR_SCRIPT}
		echo "gedit ${ERROR_FILE} +${ERROR_LINE}" >> ${ERROR_SCRIPT}
		echo "echo \"Open ${ERROR_FILE} at line ${ERROR_LINE}\"" >> ${ERROR_SCRIPT}
		echo "echo \"because of error: \"" >> ${ERROR_SCRIPT}
		ESCAPE_ERRORS=`echo ${ERRORS} | sed 's|["'\''\`]||g'`
		echo "echo \"   ${ESCAPE_ERRORS} \"" >> ${ERROR_SCRIPT}
		chmod a+x ${ERROR_SCRIPT}
		msg_error "There are errors! Run ./check_error.sh"
	else
		msg_info "There are no errors found"
	fi
}
 
check_warnings() {
        msg_debug "Check for warnings"
        WARNINGS=`cat ${LOG_FILE} | grep "warning"`
        WARNING_SCRIPT=../check_warning.sh
        rm -f ${WARNING_SCRIPT}
        if [ -n "$WARNINGS" ]; then
                WARNING_FILE=`cat ${LOG_FILE} | grep "warning" | cut -d':' -f1`
                WARNING_LINE=`cat ${LOG_FILE} | grep "warning" | cut -d':' -f2`
                echo "gedit ${WARNING_FILE} +${WARNING_LINE}" >> ${WARNING_SCRIPT}
                chmod a+x ${WARNING_SCRIPT}
                msg_error "There are warnings! Run ./check_warning.sh"
        else
                msg_info "There are no warnings found"
        fi
}
 
make_and_check() {
        MAKE_COMMAND="${MAKE_VERBOSITY} ${MAKE_TIMING} make -j${CORES} ${PIPE_TO_FILE}"
        msg_debug "We will perform the following command:${MAKE_COMMAND}"
        eval ${MAKE_COMMAND}
 
        check_errors
        check_warnings
}

final_install() {
	make install
}

build() {
 	# Create another directory to build out-of-source
        BUILD_DIR="build_${target}"
        mkdir -p ${BUILD_DIR}
        cd ${BUILD_DIR}
 
        set_cores
        set_verbosity
        set_timing
        set_logging
 
#       msg_info "We use the toolchain and disable the tests because of some awkward error"
#        msg_info "Note that CMAKE_TOOLCHAIN_FILE will only be used on the first run"
#        msg_info "it is not allowed to change an existing build tree"
#        msg_info "see: http://www.cmake.org/pipermail/cmake/2011-February/042554.html"
#        cmake -C ../${target}.initial.cmake -DCMAKE_TOOLCHAIN_FILE=../$target.toolchain.cmake \
#                ..
        cmake ..
 
        make_and_check
#	final_install
 
        msg_info "The result of our compilation efforts:"
        cd ..
        msg_info "$(file ${BUILD_DIR}/$modulename)"

}
 
msg_info "Build for platform $target"
build

