include ../Mk/local.mk

OBJS=$(patsubst %.cpp,%.o,$(wildcard *.cpp))
OBJSC=$(patsubst %.c,%.o,$(wildcard *.c))
OBJS+=$(OBJSC)

CXXINCLUDE+=-I./  -I../common 
CXXFLAGS+=-Wall

# The camera (in grab.h) needs linux/videodev.h, but should be automatically included!

all: $(OBJS)

.cpp.o:
	$(CXX)  $(CXXFLAGS) $(CXXDEFINE) -c  $(CXXINCLUDE) $< 

.c.o:
	$(CC)  $(FLAGS) $(CXXDEFINE) -c  $(CXXFLAGS) $(CXXINCLUDE) $< 

clean:
	$(RM) $(OBJS)

