#!/bin/bash

PROGRAM="aimupdate"

VERSION="$PROGRAM 0.1"

####################################################################################################
# Default configuration
####################################################################################################

# Installation paths
RUR_BIN_PATH=/usr/bin
RUR_SHARE_PATH=/usr/share/rur
RUR_TEMPLATE_PATH=$RUR_SHARE_PATH/templates
RUR_BACKENDS_PATH=$RUR_SHARE_PATH/backends
RUR_CONFIG_PATH=/etc/rur

# Configuration files
RUR_CONFIG_FILE_BACKENDS=${RUR_CONFIG_PATH}/backends.conf
RUR_CONFIG_FILE_BACKENDS_CMAKE=${RUR_CONFIG_PATH}/backends.cmake

# Prepend with destination dir if DESTDIR is present
RUR_SHARE_PATH="$DESTDIR/$RUR_SHARE_PATH"
RUR_TEMPLATE_PATH="$DESTDIR/$RUR_TEMPLATE_PATH"
RUR_BACKENDS_PATH="$DESTDIR/$RUR_BACKENDS_PATH"
RUR_CONFIG_PATH="$DESTDIR/$RUR_CONFIG_PATH"

####################################################################################################
# User configuration
####################################################################################################

if [ -e ${RUR_CONFIG_FILE_BACKENDS} ]; then
	source $RUR_CONFIG_FILE_BACKENDS
fi

####################################################################################################
# Checks
####################################################################################################

if [[ "$1" == "" ]]
then
	echo "No args supplied! Run $0 -h for more info"
	exit 1
fi

if [[ "$1" == "-h" ]]
then
	echo $VERSION \- Usage
	echo 
	echo $PROGRAM \"ModuleName\"
	echo
	exit 0 
fi 

modulename="$1"

# Check if there are no whitespaces
mn_sanity_check=${modulename//[[:space:]]}

if [[ "$mn_sanity_check" == "$1" ]]; then
	if [[ "$1" == *Module ]]; then
		echo "Update $1"
	else
		echo "Please, end the module with \"Module\""
		exit 1
	fi
else
	echo "Please, do not use whitespaces"
	exit 1
fi

####################################################################################################
# Start
####################################################################################################

cd "$modulename"

echo "[#] Update the scripts"
cp $RUR_TEMPLATE_PATH/build.sh aim/scripts
cp $RUR_TEMPLATE_PATH/run.sh aim/scripts

echo "[#] Update build process files"
cp $RUR_TEMPLATE_PATH/cmake/* aim/cmake
cp $RUR_TEMPLATE_PATH/*.xml aim
cp $RUR_TEMPLATE_PATH/*.cmake aim
cp $RUR_TEMPLATE_PATH/CMakeLists.txt aim

thispath=$(pwd)
echo "[#] We do not update CMakeLists.txt because this might be adjusted by you"
echo "[#]  to see do: diff $thispath/CMakeLists.txt $RUR_TEMPLATE_PATH/CMakeLists.parent.txt"
read -p "[#] Do you want to see that now (y/N)? " lookatdiff
if [ "${lookatdiff}" == "y" ]; then
	cp $RUR_TEMPLATE_PATH/CMakeLists.txt.parent CMakeLists.txt.temp
	sed -i "s/TemplateModule/$modulename/g" CMakeLists.txt.temp
	diff --report-identical-files CMakeLists.txt.temp CMakeLists.txt
	rm CMakeLists.txt.temp
fi

cp $RUR_TEMPLATE_PATH/Makefile.parent ./Makefile

# Replace "template module name" by real name
echo "[#] In copied files replace TemplateModule by $modulename"
sed -i "s/TemplateModule/$modulename/g" aim/scripts/build.sh
sed -i "s/TemplateModule/$modulename/g" Makefile

